//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OCXDemo.rc
//
#define IDCANCEL_REFLESH                3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_OCXDEMO_DIALOG              102
#define IDD_DEMO_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDI_ICON_VIDEO_PLAY             146
#define IDI_ICON_VIDEO_PLAY_OVER        147
#define IDR_MENU_POP                    166
#define IDD_DLG_3G_FLOW_CONFIG          237
#define IDC_EDIT_DAY_USED               1000
#define IDC_EDIT_SERVER_IP              1001
#define IDC_EDIT_MONTH_USED             1001
#define IDC_EDIT_SERVER_PORT            1002
#define IDC_EDIT_MONTH_HAVE             1002
#define IDC_EDIT_DEV_ID                 1003
#define IDC_COMBO_CHANNEL               1004
#define IDC_EDIT_TO_PAY_DAY             1004
#define IDC_BUTTON_FULL                 1005
#define IDC_EDIT_MONTH_LIMINT           1005
#define IDC_EDIT_MONTH_USED_CONFIG      1005
#define IDC_COMBO_SEARCH_CHANNEL        1006
#define IDC_EDIT_DAY_LIMINT             1006
#define IDC_COMBO_WND                   1007
#define IDC_EDIT_PAY_DAY                1007
#define IDC_BUTTON_STOP                 1008
#define IDC_EDIT_DAY_REMIND             1008
#define IDC_EDIT_EVERY_TELL             1008
#define IDC_BUTTON_OPEN_SOUND           1009
#define IDC_EDIT_MONTH_REMIND           1009
#define IDC_EDIT_MONTH_TELL_TO          1009
#define IDC_BUTTON_PIC                  1010
#define IDC_BUTTON_TALK_BACK            1011
#define IDC_BUTTON_MONITOR              1012
#define IDC_BUTTON_START_RECORD         1013
#define IDC_BUTTON_STOP_RECORD          1014
#define IDC_BUT_CLEAR                   1014
#define IDC_BUTTON_ALL_PIC              1015
#define IDC_BUT_CORRECT                 1015
#define IDC_COMBO_WND_LAYOUT            1016
#define IDC_BUTTON_SELECT_PATH          1017
#define IDC_EDIT_PICTURE_SAVE_PATH      1018
#define IDC_BUTTON_AUTO_CLOSE_TIME      1019
#define IDC_EDIT_AUTO_CLOSE_TIME        1020
#define IDC_EDIT_RECORD_SPLIT_TIME      1021
#define IDC_BUTTON_REC_SPLIT_TIME       1022
#define IDC_COMBO_DISK_NO_SPACE_OPERATE_TYPE 1023
#define IDC_BUTTON_SAVE_PICTURE_PATH    1024
#define IDC_BUTTON_DISK_NO_SPACE        1025
#define IDC_EDIT_RESERVED_SPACE         1026
#define IDC_BUTTON_RESERVED_SPACE       1027
#define IDC_BUTTON_PIC_DEV              1028
#define IDC_BUTTON_PIC_ALL              1029
#define IDC_BUTTON_OCX_BK               1044
#define IDC_GVIEWERCTRL                 1050
#define IDC_OCXCTRL                     1050
#define IDC_BUTTON_SET_TITLE            1051
#define IDC_EDIT_TITLE                  1052
#define IDC_COMBO_VIDEO_MODE            1053
#define IDC_BTN_UP                      1054
#define IDC_BTN_CRUISE                  1055
#define IDC_BTN_DOWN                    1056
#define IDC_BTN_LEFT                    1057
#define IDC_BTN_RIGHT                   1058
#define IDC_SLIDER_SPEED                1059
#define IDC_BTN_ZOOM_DEL                1060
#define IDC_BTN_ZOOM_ADD                1061
#define IDC_BTN_LIGHT_DEL               1062
#define IDC_BTN_LIGHT_ADD               1063
#define IDC_BTN_FOCUS_DEL               1064
#define IDC_BTN_FOCUS_ADD               1065
#define IDC_EDIT_PONIT                  1066
#define IDC_BTN_PRESET_SET              1067
#define IDC_BTN_PRESET_MOVE             1068
#define IDC_BTN_PRESET_DEL              1069
#define IDC_BTN_LIGHT                   1070
#define IDC_BTN_WIPER                   1071
#define IDC_BTN_LEFT_UP                 1072
#define IDC_BTN_RIGHT_UP                1073
#define IDC_BTN_RIGHT_DOWN              1074
#define IDC_BTN_LEFT_DOWN               1075
#define IDC_SPIN_POINT                  1077
#define IDC_CMSV6OCXCTRL                1082
#define IDC_COMBO_WND_SHOW              1090
#define IDC_EDIT_DEV_IDNO               1091
#define IDC_COMBO_LOCATION              1092
#define IDC_COMBO_FILE_TYPE             1093
#define IDC_DATETIMEPICKER_SEARCH_TIME  1094
#define IDC_COMBO_FILE_ATTRIBUTE        1095
#define IDC_LIST_FILE                   1096
#define IDC_BUTTON_SEARCH               1097
#define IDC_COMBO_VIEW_SIZE             1098
#define IDC_COMBO_VIEW_ARRANGE          1099
#define IDC_BUTTON_GET_ACTIVE_WND       1100
#define IDC_BUTTON_SET_ACTIVE_WND       1101
#define IDC_BTN_GPS                     1102
#define IDC_BTN_BROADCAST               1103
#define IDC_ED_GPSDEV                   1104
#define IDC_ST_GPS                      1105
#define IDC_BTN_ONLINE                  1106
#define IDC_ED_GPSDEV_BROADCAST         1107
#define IDC_BUTTON_3G_NET               1108
#define IDC_BUTTON_3G_NET_SET           1109
#define IDC_STATIC_TO_PAY_DAY           1261
#define IDC_STATIC_DAY_REMIND           1262
#define IDC_STATIC_TODAY_USER           1273
#define IDC_STATIC_MONTH_USER           1274
#define IDC_STATIC_MONTH_HAVE           1275
#define IDC_STATIC_MONTH_LMT            1276
#define IDC_STATIC_MONTH_TELL_TO        1277
#define IDC_STATIC_PAY_DAY              1278
#define IDC_STATIC_DAY_LIMIT            1279
#define IDC_STATIC_ENABLE_MONITOR       1280
#define IDC_COMBO_ENABLE_MONITOR        1281
#define IDC_STATIC_TIP_INFO             1282
#define IDC_STATIC_STATUS_3G            1283
#define IDC_STATIC_DAY                  1284
#define IDC_STATIC_D                    1285
#define IDC_STATIC_SET_3G               1286
#define IDC_STATIC_1                    1288
#define IDC_STATIC_2                    1289
#define IDC_STATIC_3                    1290
#define IDC_STATIC_5                    1292
#define IDC_STATIC_6                    1293
#define IDC_STATIC_7                    1294
#define IDC_CHECK_DAY_REMIND            1403
#define IDC_CHECK_MONTH_REMIND          1404
#define IDC_STATIC_FLOW_ALARM           1405
#define ID_MENU_RECSEARCH_PLAY          32771
#define ID_MENU_RECSEARCH_DOWN          32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
